version: '3.4'

services:
  postgres:
    image: postgres:latest
    container_name: ${CONTAINER_NAME}
    hostname: ${DB_HOSTNAME}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL",  "pg_isready -d keep-this -U keep-this-user"]
      timeout: 10s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dev-network

  api:
    image: ${IMAGE_NAME}   
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dev-network

volumes:
  postgres_data:

networks:
  dev-network:
    driver: bridge
