name: CI & CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v1.5.0
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore dependencies
        run: dotnet restore "./API.KeepThis/API.KeepThis/API.KeepThis.csproj"
        
      - name: Build
        run: dotnet build "./API.KeepThis/API.KeepThis/API.KeepThis.csproj" --no-restore
        
      - name: Publish
        run: dotnet publish "./API.KeepThis/API.KeepThis/API.KeepThis.csproj" --no-restore

    # Removed the test step since there are no tests yet
    # - name: Run tests
    #   run: dotnet test --no-restore --verbosity normal
    
  deploy-DockerHub:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/keep-this-api:latest -f .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/keep-this-api:latest
        
  deploy-VPS:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH VPS and deploy
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PWD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            export IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/keep-this-api:latest
            export DB_HOSTNAME=${{ secrets.DB_HOSTNAME }}
            export DB_NAME=${{ secrets.DB_NAME }}
            export DB_USER=${{ secrets.DB_USER }}
            export DB_PWD=${{ secrets.DB_PWD }}
            export CONTAINER_NAME=${{ secrets.CONTAINER_NAME }}         
            cd .
            docker-compose down
            docker-compose pull
            docker-compose up -d
