name: CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore "./API.KeepThis/API.KeepThis/API.KeepThis.csproj"

    - name: Build
      run: dotnet build "./API.KeepThis/API.KeepThis/API.KeepThis.csproj" --no-restore

    # Removed the test step since there are no tests yet
    # - name: Run tests
    #   run: dotnet test ./path/to/your/Test.csproj --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish "./API.KeepThis/API.KeepThis/API.KeepThis.csproj" -c Release -o out

